### ISSUE TITLE
unitialized variables ?

### ISSUE THREAD

**Issue by DvonHolten** [karpiu/kp-minisatp#1]
the local vars tmp and singles seem not to be initialized before they are used a few lines down.
how can this work ? or do i miss something?

https://github.com/karpiu/kp-minisatp/blob/87765b43dbedde5dba21910da9976e0ce2045d56/Hardware_sorters.cc#L143

**Comment by marekpiotrow** [comment]
They are initialized as empty vectors by the default constructor.
